FROM xpod-base

RUN add-apt-repository ppa:xtradeb/apps -y \
    && apt-get update \
    && apt-get install -y chromium \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN useradd -m -U -s /bin/bash chrome

COPY <<'EOF' /app.sh
#!/bin/bash
set -e

CHROMIUM_WIDTH=${RESOLUTION%%x*}
CHROMIUM_HEIGHT=${RESOLUTION#*x}; CHROMIUM_HEIGHT=${CHROMIUM_HEIGHT%%x*}
su -c "chromium --disable-gpu --start-maximized --window-size=${CHROMIUM_WIDTH},${CHROMIUM_HEIGHT} --force-device-scale-factor=1" chrome

EOF

RUN chmod +x /app.sh
