FROM xpod-base

RUN add-apt-repository ppa:xtradeb/apps -y \
    && apt-get update \
    && apt-get install -y chromium \
    && apt-get install -y socat \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN useradd -m -U -s /bin/bash chrome

COPY app.sh /app.sh
RUN chmod +x /app.sh

EXPOSE 9222
